### ISSUE TITLE
Multiple packages same name 

### ISSUE THREAD

**Issue by maddrid** [codexilab/osclass-packages#11]
Adding multiple packages with same name should not be allowed .

**Comment by codexilab** [comment]
I was thinking about it for a while, I think you're right, there is no need to allow packages with the same name.

Unless they are for different types of accounts. @web-media what do you think about this?

**Comment by maddrid** [comment]
Hy @codexilab . Allow packages with  the same name seems the wright option . 
'Gold' package for User , and Gold package for Company . I'm a little busy right now to dive deeper  , but i'm keeping close tabs  with the project.

**Comment by codexilab** [comment]
Thank you very much that. Then, this issue will be open for now.
