### ISSUE TITLE
packages_before_update_profile

### ISSUE THREAD

**Issue by maddrid** [codexilab/osclass-packages#12]
packages assigned to user  not removed when switching from user to company and viceversa .
Is intended behaviour ? 
```php
function packages_before_update_profile() {
     print_r(Params::getParamsAsArray());
     var_dump(osc_logged_user_type());
     var_dump(!Params::getParam('b_company'));
     var_dump((bool)Params::getParam('b_company'));
     var_dump(Params::getParam('b_company'));
        exit();
```
 in my case user is company and not altered on submit
 [b_company] => 1 
 bool(false)  =>   var_dump(osc_logged_user_type()); //  something is wrong
bool(false) 
bool(true) 
string(1) "1" 
since Params::getParam('b_company') is always present  0 or 1 ,
a   comparation between  (bool)Params::getParam('b_company') !== osc_logged_user_type() {
remove packages
} 
  can replace duplicate code in if if else if 
```php
 if (Params::getParam('b_company')) {

                // Deleting of all about the current assignment
                $items = Item::newInstance()->findByUserID(osc_logged_user_id());
                if ($items) {
                    foreach ($items as $item) {
                        Packages::newInstance()->delItemRelationByItemId($item['pk_i_id']);
                    }
                }
                Packages::newInstance()->deleteAll(osc_logged_user_id());
            }
```

**Comment by codexilab** [comment]
> packages assigned to user not removed when switching from user to company and viceversa .
> Is intended behaviour ?

It seems that the hook 'pre_user_post' only it work from the user's own profile logged, not from oc-admin panel.
